config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('subjects/', include('subjects.urls', namespace='subjects.subjects')),
    path('classboard/', include('classboard.urls')),
    path('students/', include('students.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('testimonials/', include('testimonials.urls', namespace='testimonials.testimonials')),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),

    path("accounts/", include("django.contrib.auth.urls")),
    path("login/", auth_views.LoginView.as_view(template_name = "login.html"), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

teachers/urls.py
from django.urls import path
from .views import view_teachers, TeacherCreateView, TeacherDeleteView, TeacherUpdateView

app_name = 'teachers'

urlpatterns = [
    path('', view_teachers, name='view_teachers'),
    path('<int:pk>/', view_teachers, name='view_teacher'),
    path('create/', TeacherCreateView.as_view(), name='create_teachers'),
    path('<int:pk>/update',TeacherUpdateView.as_view(),name='update_teachers'),
    path('<int:pk>/delete',TeacherDeleteView.as_view(), name='delete_teachers')


]

wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    path('', show_teachers_grid, name='show_teachers_grid'),
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

teachers/models.py
from django.db import models

from persons.models import PersonAbstract


class Teacher(PersonAbstract):
    subject = models.ManyToManyField(to='subjects.Subject', related_name='subject_teacher')

    class Meta:
        verbose_name = 'Учитель'
        verbose_name_plural = 'Учителя'

        ordering = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('teachers:view_teacher', kwargs={'pk': self.pk})

teachers/forms.py
from django import forms
from .models import Teacher

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Имя'
            }),
            'last_name': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Фамилия'
            }),
            'phone': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Телефон'
            }),
            'email': forms.EmailInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Email'
            }),
            'image': forms.FileInput(attrs={'class': 'img-fluid'}),

            'oubject': forms.SelectMultiple(attrs={'class': 'form-control', 'style': 'max-width: 300px;'})
        }  

teachers/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.crypto import get_random_string
from django.views.generic import DeleteView, UpdateView, CreateView 
from .models import Teacher
from django.urls import reverse_lazy
from .forms import TeacherForm
# Create your views here.
def view_teachers(request, pk=None) -> render:
    
    if 'create' in request.path:
        Teacher.objects.update_or_create(first_name='Кравец', defaults={
                'last_name': get_random_string(length=15, allowed_chars='АБВГДЕЁЖЗИКЛМНОПРСТУФХЧШЩЭЮЯ'),
                'birth_day':'2000-12-15',
                'email':'bob@kravetz.eau',
                'phone':'+998901002030'
            }
        )

        teacher_tmp = Teacher.objects.filter(first_name='Кравец').select_related('first_name').first()
        teacher_tmp.email = (get_random_string(length=6, allowed_chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789')+'@kravetz.eau')
        teacher_tmp.phone = ("+"+get_random_string(length=13, allowed_chars='0123456789'))
        
        teacher_tmp.save(update_fields=['phone'])
               
       
    if pk:
        current_teacher = get_object_or_404(Teacher, pk=pk)
        template = 'teacher_detail.html'
        context = {
            'current_teacher': current_teacher,
        }
    else:        
        teachers = Teacher.objects.prefetch_related('subject').order_by('first_name').all()
        template = 'teachers.html'
        context = {
            'teachers': teachers,
        }
    
       
    return render(request=request, template_name=template, context=context)
    
class TeacherCreateView(CreateView):
    success_url = reverse_lazy('teachers:view_teachers')
    template_name = 'teachers_create.html'
    form_class = TeacherForm
    model = Teacher

class TeacherUpdateView(UpdateView):
    success_url = reverse_lazy('teachers:view_teachers')
    template_name = 'teachers_create.html'
    form_class = TeacherForm
    model = Teacher

class TeacherDeleteView(DeleteView):
    success_url = reverse_lazy('teachers:view_teachers')
    template_name = 'teachers_delete.html'
    model = Teacher

teachers/templates/teacher_detail.html
{% extends 'layout/base.html' %}
{% block title %}Учитель{% endblock title %}

{% block content %}
    <div class="row-fluid">
        <div class="col-12">
            <h2>{{ current_teacher.first_name }} {{ current_teacher.last_name }}</h2>
            <p>{{ current_teacher.birth_day|date:"d M y"}}</p>
            <p>{{ current_teacher.email }}</p>
            <p>{{ current_teacher.phone }}</p>
            <p><a class="btn btn-primary" href="{% url 'teachers:view_teachers'  %}"> Обратно </a></p>
            <p><a class="btn btn-primary" href="{% url 'teachers:delete_teachers' current_teacher.pk %}"> Удалить </a></p>
            <p><a class="btn btn-primary" href="{% url 'teachers:update_teachers' current_teacher.pk %}"> Изменить </a></p>
        </div>
    </div>
{% endblock content %}

teachers/templates/teachers.html
{% extends 'layout/base.html' %}
{% block title %}Учителя{% endblock title %}

{% block content %}
    {% for teacher in  teachers %}
        <h2>{{ teacher.first_name }} {{ teacher.last_name }}</h2>
        <a class="btn btn-primary" href="{{ teacher.get_absolute_url }}"> Перейти </a>
    {% endfor %}
{% endblock content %}

teachers/templates/teachers_create.html
{% extends 'layout/base.html' %} 
{% block title %} Добавить/Изменить учителя {% endblock title %} 

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Добавить/Изменить учителя</h3>
          <div class="row">
            <div class="col-md-12">
              <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                  Отправить
                </button>
                <a class="btn btn-info" href="{% url 'teachers:view_teachers' %}">Список учителей</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

teachers/templates/teachers_delete.html
{% extends 'layout/base.html' %}


{% block title %}
    Удалить {{ object }}
{% endblock title %}
    


{% block content %}
    <form method="post" action="{% url 'teachers:delete_teachers' object.pk %}">
        {% csrf_token %}
        <h3>Вы уверены, что хотите удалить студента {{ object }}?</h3>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'teachers:view_teachers' %}" class="btn btn-primary">Отмена</a>
    </form>
    
{% endblock content %}